apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: socios-tenis
  labels:
    app: grafana
    component: server
    managed-by: socios-tenis
    part-of: observability
  annotations:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.socios-tenis.svc.cluster.local:9090
        isDefault: true
        editable: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: socios-tenis
  labels:
    app: grafana
    component: server
    managed-by: socios-tenis
    part-of: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      component: server
  template:
    metadata:
      labels:
        app: grafana
        component: server
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.2
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: socios-tenis
  labels:
    app: grafana
    component: server
    managed-by: socios-tenis
    part-of: observability
spec:
  type: NodePort
  selector:
    app: grafana
    component: server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30300
